---
###############################################################################
# PYTHON APPLICATION PIPELINE
###############################################################################

include:
  - project: 'inuits/gitlab-ci/pipeline-templates'
    file: 'pip-pipeline.yml'
    ref: 'v1.5.4'
  - project: 'inuits/gitlab-ci/pipeline-deploy-targets'
    file: 'extra-targets.yml'
    ref: 'main'
    
variables:
  CUSTOMER: 'inuits'
  APPLICATION: 'dams-storage'
  SKIP_DEPLOY: 'true'
