---
###############################################################################
# PYTHON APPLICATION PIPELINE
###############################################################################

include:
  - project: 'inuits/gitlab-ci/pipeline-templates'
    file: 'pip-pipeline.yml'
    ref: 'v1.7.1'
  - project: 'rnd/inuits/dams/pipeline-deploy-targets'
    file: 'deployment-targets.yml'
    ref: 'master'

variables:
  CUSTOMER: 'inuits'
  APPLICATION: 'dams-storage'
  SKIP_DEPLOY: 'true'
