---
include:
  - project: 'inuits/gitlab-ci/pipeline-templates'
    ref: 'v4.1.0'
    file: 
      - '/pipelines/customers/dams/deliver-multi-customer.yml'
      - '/jobs/build-variant/pip.yml'

variables:
  PROJECT: 'dams'
  APPLICATION: 'storage'

  HARBOR_PROJECT_DEV: elody-dams-dev

customer:
  parallel:
    matrix:
      - CUSTOMER:
        - amvb
        - coghent
        - digipolis
        - vliz
