---
###############################################################################
# COMMON APPLICATION PIPELINE
###############################################################################

include:
  - project: 'inuits/gitlab-ci/pipeline-templates'
    file: 
      - 'common-pipeline.yml'
#    ref: 'v1.0.2'
    
variables:
  CUSTOMER: 'inuits'
  APPLICATION: 'dams-storage'
  CONSUL_HTTP_ADDR: 'https://consul.service.consul:8501'
  CONSUL_HTTP_SSL_VERIFY: 'false'
  REGISTRY_PROXY: 'nexus.inuits.io:6011'
  TERRAFORM_IMAGE: 'dams-terraform'
  TERRAFORM_TAG: 'latest'
