---
###############################################################################
# PYTHON APPLICATION PIPELINE
###############################################################################

include:
  - project: 'inuits/gitlab-ci/pipeline-templates'
    file: 'pip-pipeline.yml'
    ref: 'v1.6.2'
  - project: 'rnd/inuits/dams/pipeline-deploy-targets'
    file: 'extra-targets.yml'
    ref: 'main'
    
variables:
  CUSTOMER: 'inuits'
  APPLICATION: 'dams-storage'
  SKIP_DEPLOY: 'true' # This pipeline does not provide a deploy, if a deploy is needed, you can add it to the deploy targets mentioned in the includes
