---
###############################################################################
# PYTHON APPLICATION PIPELINE
###############################################################################

include:
  - project: 'inuits/gitlab-ci/pipeline-templates'
    file: 'pip-pipeline.yml'
    ref: 'v1.6.2'

variables:
  CUSTOMER: 'inuits'
  APPLICATION: 'dams-storage'
  SKIP_DEPLOY: 'true'
