---
###############################################################################
# PYTHON APPLICATION PIPELINE
###############################################################################

include:
  - project: 'inuits/gitlab-ci/pipeline-templates'
    file: 'pip-pipeline.yml'
    ref: 'v1.7.0'
  - project: 'customers/coghent/infra/coghent-infra-gitlab-templates'
    file: 'common-pipeline.yml'
    ref: 'master'

variables:
  CUSTOMER: 'inuits'
  APPLICATION: 'dams-storage'
  SKIP_DEPLOY: 'true'
