---
include:
  - project: 'inuits/gitlab-ci/pipeline-templates'
    ref: 'v2.2.0'
    file: 
      - '/pipelines/multi-customer-delivery.yml'
      - '/jobs/build-variant/pip.yml'

variables:
  PROJECT: 'dams'
  APPLICATION: 'storage'

customer:
  parallel:
    matrix:
      - CUSTOMER:
        - digipolis
        - coghent
